FROM postgres:9.6-alpine

#COPY init.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_MULTIPLE_DATABASES=jrvstrading
ENV POSTGRES_MULTIPLE_DATABASES=jrvstrading_testing